# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

############################## Auto start ##############################

# Make sure the notebook display is set as primary
exec_always --no-startup-id xrandr --output $ntb-display --primary

# Disable bell
#exec --no-startup-id xset -b

# Cap CD-ROM drive's speed at 4x
#exec --no-startup-id eject --cdspeed 4

# Set the default volume to 50%
exec --no-startup-id pactl set-sink-volume 0 '50%'

# Make sure dunst runs as the notification daemon - provided by x11-misc/dunst
exec --no-startup-id dunst

# GLava - spectrum visualizer - provided by x11-apps/glava from 'sk-overlay'
#exec --no-startup-id glava --desktop

# Clipmenu daemon - provided by x11-misc/clipmenu
exec --no-startup-id clipmenud

# Load X resources configuration
exec_always --no-startup-id xrdb -load ~/.Xresources

# urxvtd - terminal emulator daemon - provided by x11-terms/rxvt-unicode
exec --no-startup-id urxvtd --quiet --opendisplay --fork

# Firefox/Nightly via gtk-launch - provided by x11-libs/gtk+
#exec cd ~/.local/share/applications && gtk-launch Nightly.desktop

# Discord - provided by net-im/discord-bin
exec --no-startup-id discord

# udiskie - removable media auto-mount (tray icon enabled) - provided by sys-fs/udiskie
exec --no-startup-id udiskie --smart-tray

# atuin - shell history manager - provided by app-shells/atuin
exec --no-startup-id atuin daemon

# xscreensaver - lock the screen after 4min - provided by x11-misc/xscreensaver
exec --no-startup-id xscreensaver --no-splash

# feh - set wallpaper - provided by media-gfx/feh
set $wallpaper ~/.config/i3/feh/wallpaper.jpg
exec --no-startup-id feh --bg-scale $wallpaper

# redshit - eye saver - provided by x11-misc/redshift
exec --no-startup-id redshift-gtk

# xiccd - X to colord bridge - provided by x11-misc/colord and x11-misc/xiccd
exec --no-startup-id xiccd

# nm-applet - network manager - provided by gnome-extra/nm-applet
#exec --no-startup-id nm-applet

# picom - standalone compositor (Conky transparency) - provided by x11-misc/picom
exec_always --no-startup-id picom --daemon

# conky - desktop status - provided by app-admin/conky
exec --no-startup-id conky --config ~/.config/conkyrc.lua

# hack the Systemd graphical target in
exec --no-startup-id systemctl --user start i3-session.target
