#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>
# Copyright (C) 2018 1969yuri1969 <1969yuri1969@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

INTERFACE="${BLOCK_INSTANCE:-wlan0}"

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    [[ "$(cat "/sys/class/net/$INTERFACE/operstate")" = 'down' ]] && exit

#------------------------------------------------------------------------

# Max link quality
MAX_QUALITY=70
# Requires kernel with CFG80211=y
QUALITY=$(grep "$INTERFACE" /proc/net/wireless | awk -v max="$MAX_QUALITY" '{ print int($3 * 100 / max) }')

#------------------------------------------------------------------------

echo "${QUALITY}% " # full text
echo " " # short text

# color
if [[ $QUALITY -ge 80 ]]; then
    # greeen
    echo "#A8FF00"
elif [[ $QUALITY -lt 80 && $QUALITY -ge 60 ]]; then
    # ltgreen
    echo "#82D700"
elif [[ $QUALITY -lt 60 && $QUALITY -ge 40 ]]; then
    # yellow
    echo "#C69A00"
elif [[ $QUALITY -lt 40 ]]; then
    # red
    echo "#ED322F"
fi
